### ISSUE TITLE
Mapreduce Bootstrap controller

### ISSUE THREAD

**Issue by plutoshe** [taskgraph/taskgraph#108]
To give user a convenient to call interface, it is necessary to implement a code to serve as a kubernetes node/shell program implemented before. 
Follow logical of my current code, it provide user a start api to receive their configuration to start. 
Then it will run automatically, check the required configuration, replenish default configuration, and start controller and task node based on configuration.

**Comment by fengjingchao** [comment]
I'm not getting it..
Can you give an example why it's needed...

**Comment by plutoshe** [comment]
Mapreduce Bootstrap controller is not the required ( as same logic as the regrssion/demo/main.go).
In other words, it just a transition program to run a mapreduce framework.

**Comment by fengjingchao** [comment]
So this is something to run the user program, right?
I think this is fine. Please submit the code and link to this issue.

**Comment by plutoshe** [comment]
Yeah, that's what I mean.

**Comment by fengjingchao** [comment]
Please separate the bootstrap code in single PR.

**Comment by plutoshe** [comment]
Well, I will do it.
