### ISSUE TITLE
Roadmap for taskgraph future improvement

### ISSUE THREAD

**Issue by fengjingchao** [taskgraph/taskgraph#19]
Thanks Xiaoyun for the update and discussion.

- Run BWMF successfully.
- Move TaskGraph gradually to new APIs while supporting current and newly added tests.

**Comment by xiaoyunwu** [comment]
Isn't Compute is hidden from framework, framework would only know setepoch and channel supplied to Fetch? 
And Serve should not an interface as it is not used by task directly. 

Another thing I like to see if happen is to swap Context that we defined with the Context defined in thel. https://blog.golang.org/context

**Comment by fengjingchao** [comment]
The Context from golang is what I had in min when introducing it to our framework.

I just do want a dependency when we don't need all the functions at first.

**Comment by fengjingchao** [comment]
Summarizing the Fetch design here:

```Go
// ctx -- the Google context library that framework gives to user in framework callback 
// and user should pass back in any framework call.
// taskID -- the task to ask data from.
// methodName -- the gRPC method to call for serving the data
// input -- user defined arguments to call gRPC service of the other end.
// dataChan -- the channel to return requested data.
Fetch(ctx context.Context, taskID uint64, methodName string, 
      input proto.Message, dataChan chan<- proto.Message)
```

**Comment by xiaoyunwu** [comment]
adding onto it inline

**Comment by fengjingchao** [comment]
An example in regression framework:

Previously we used dataRequest:
```Go
// Ideally, we should also have the following
func (t *dummySlave) MetaReady(ctx taskgraph.Context, fromID uint64, linkType, meta string) {
	if linkType == "Parents" {
		ctx.DataRequest(fromID, meta)
	}
	if linkType == "Children" {
		ctx.DataRequest(fromID, meta)
	}
}
```
And in
```Go
func (t *dummySlave) ChildDataReady(ctx taskgraph.Context, childID uint64, req string, resp []byte) {
    ... Parse Data ...
	if len(t.fromChildren) == len(t.framework.GetTopology().GetNeighbors("Children", t.epoch)) {
		... Compute ...
		t.gradientReady.Await()
		ctx.FlagMeta("Children", "GradientReady")
	}
}
```

We will change it to:
```Go
func (t *dummySlave) MetaReady(ctx context.Context, fromID uint64, linkType, meta string) {
	if linkType == "Parents" {
		t.framework.Fetch(ctx, fromID, "getParameter", paramInput, paramChan)
	}
	if linkType == "Children" {
		t.framework.Fetch(ctx, fromID, "getGradient", gradtInput, gradtChan)
	}

    go func(){
        param := <-paramChan
        gradt := <- gradtChan
        ...Compute...
        t.framework.FlagMeta(ctx, parentID, "GradientReady")
    }()
}
```

@xiaoyunwu Right?

**Comment by xiaoyunwu** [comment]
LGTM

Xiaoyun

**Comment by BaiGang** [comment]
I'd like to suggest that we provide a convenient logging service from the framework for task implementations. This is important for a distributed computing infrastructure.

**Comment by xiaoyunwu** [comment]
good point, that is something that we had in mind. @Hongchao, can you come
up with a design that we can discuss?

Xiaoyun

**Comment by fengjingchao** [comment]
@BaiGang @xiaoyunwu 
Can you elaborate it?

**Comment by fengjingchao** [comment]
I'm closing this because it's a little outdated.
Please create new issues since we've more specific requirement now.
