### ISSUE TITLE
framework.DataRequest hangs in some cases

### ISSUE THREAD

**Issue by BaiGang** [taskgraph/taskgraph#47]
As metioned in https://github.com/taskgraph/taskgraph/pull/8#discussion-diff-27768327.

This happens when we respond the the grpc request with a relative longer latency, say, around 900~1200 milliseconds. 

You may run the [integration test script](https://github.com/BaiGang/taskgraph/blob/pgmethod/example/bwmf/demo/run_demo.sh) to reproduce this issue. The integration test uses [artificially generated matrix data](https://github.com/BaiGang/taskgraph/blob/pgmethod/example/bwmf/demo/gen_data.go) to prepare two row shards and two column shards for two tasks to run with them. After executing the integration test, you may check the `task-0.log` and `task-1.log` to examine what's going on and where it hangs.

Also, the events and logistics are illustrated in this [wiki](https://github.com/taskgraph/taskgraph/wiki/Implementing-block-wise-matrix-factorization-on-taskgraph#time-series).

**Comment by xiaoyunwu** [comment]
@Hongchao, can you take a look?

Xiaoyun

**Comment by fengjingchao** [comment]
I'm reading the code and afterwards I will try to reproduce the problem. It might take some time.

**Comment by fengjingchao** [comment]
I couldn't reproduce it.
If you encounter again please upload the log file.
At the mean time, I think the bwmf task isn't completed with the meta ready from all tasks. I would like to see a test having a successful run. Please refer to:

https://github.com/BaiGang/taskgraph/blob/pgmethod/integration/regression_framework_test.go

**Comment by xiaoyunwu** [comment]
Hi, Gang,

When do you have time, I like to get together to see what is happening. We
can debug together.

Xiaoyun

**Comment by BaiGang** [comment]
@fengjingchao One of the task doesn't send meta ready becausu it blocks at getD with checking grpc context. That is issue we are going to address here. After executing the run_demo.sh, do you see two task log files task-0.log and task-1.log? In every run, one of the tasks hangs there.

@xiaoyunwu Let's meet tomorrow morning.

**Comment by fengjingchao** [comment]
How do you define "hangs there"?
I can see one of the task flag the meta while the other doesn't. However, all checkGRPCContext returns with logging pairs:
```
 Before checking GRPC status...
After checking GRPC status:  <nil>
```

**Comment by xiaoyunwu** [comment]
Hi, Gang,

Are you coming today? Thanks.

Xiaoyun

**Comment by BaiGang** [comment]
As we moved on to identify the issue, we found that it actually blocks at this line of code https://github.com/taskgraph/taskgraph/blob/master/framework/data_request.go#L58. 

Sorry for the misleading issue report.
