### ISSUE TITLE
TODO for BWMF

### ISSUE THREAD

**Issue by fengjingchao** [taskgraph/taskgraph#58]
- Fix the race #56 
- File system logic should be wrapped in creating a client. Get rid of `createReader`
- single combined representation for matrix shard
- Output should be an function interface so that we can have different ways to use final result: logging, writing to file, send to channel in testing, etc.

**Comment by BaiGang** [comment]
For a single combined representation for matrix shard, one solution is to use a [union in proto](https://developers.google.com/protocol-buffers/docs/techniques?csw=1#union). But it still requires repetitive code to handle dense/sparse cases. Another solution is to just use the sparse representation as [discussed in this commit](https://github.com/BaiGang/taskgraph/commit/1ebbef5931cddd330a9a42ed7653eb3652784ada#commitcomment-10681656). I prefer the latter.

**Comment by 5kg** [comment]
@BaiGang Another option is `oneof` feature (https://developers.google.com/protocol-buffers/docs/reference/java-generated#oneof) if it's not removed in proto3.

**Comment by xiang90** [comment]
@5kg `oneof` is not supported by `go-protobuf` as far as I know. It would generate a bunch of Getters.
